FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Compilar la aplicación
RUN npm run build

# Exponer el puerto para preview (por defecto, Vite preview usa 4173, pero puedes ajustar)
EXPOSE 5173

# Comando para servir la aplicación compilada
CMD ["npm", "run", "preview"]
